# Generated by Django 3.0.3 on 2020-03-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200225_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datasources',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('wgroup', models.CharField(max_length=45)),
                ('wserver', models.CharField(max_length=45)),
                ('type', models.IntegerField()),
                ('source', models.CharField(max_length=255)),
                ('putindb', models.IntegerField(blank=True, null=True)),
                ('related', models.IntegerField()),
                ('pattern', models.IntegerField(blank=True, null=True)),
                ('target', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.IntegerField()),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('excepted', models.IntegerField()),
            ],
            options={
                'db_table': 'datasources',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hadoopsources',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('state', models.IntegerField()),
                ('source', models.CharField(max_length=255)),
                ('datasource_id', models.IntegerField()),
            ],
            options={
                'db_table': 'hadoopsources',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=255)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('feature', models.IntegerField(blank=True, null=True)),
                ('hashsum', models.CharField(max_length=255)),
                ('hadoopsource_id', models.IntegerField()),
                ('format', models.CharField(max_length=45)),
                ('state', models.IntegerField()),
            ],
            options={
                'db_table': 'metadata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
